### ISSUE TITLE
Webinar #3 Topics

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi-meetups#1]
**Recap of `Strapi Webinar strapi/strapi#2`**
Today at `Strapi Webinar strapi/strapi#2`, @Mcastres walked us through how to build a full-stack blog with React, GraphQL, and Strapi.

**Your suggestions for next webinar**
As part of the initiative to provide space where to post your ideas/requests for the next `Strapi Webinar strapi/strapi#3`, please feel free to leave them below.

- each posting could be voted for with "👍", "➕" etc - you know the drill...
- the topics with most likes could be answered first, the rest - depending on, you guessed it - the time remaining...
- for each webinar (regardless of how frequent/rare they end up being) we could open a new discussion to keep things organized
- anyone - more suggestions?

PS. Big thanks to Strapi team, @Mcastres for putting together the `Strapi Webinar strapi/strapi#2`. 
Cheers to everyone who showed up 🚀 ✋

**Comment by vcoisne** [comment]
@ScottAgirs Thanks again for creating this issue. 

The [3rd Online meetup](https://app.livestorm.co/strapi-1/everything-you-need-to-know-about-strapi-deployment-options) has been announced and will take place on Thursday, March 19th at 8:0 (PDT). 

I will close this one now. We'll make sure to tweet out the next one so that we can get more suggestions and votes on topics :)
