### ISSUE TITLE
[New group] Nigeria, Port Harcourt

### ISSUE THREAD

**Issue by bigpreshy** [strapi/strapi-meetups#11]
# Background Information

- **Name**: Precious Luke
- **Company:** Hotelng
- **Country, City:** Nigeria, Port Harcourt
- **Personal Website or blog:** localhost101.medium.com
- **Twitter:** @localhost_101

# Strapi support needed

- [ ] Finding speakers
- [x] Finding host venues
- [x] Finding sponsors
- [x] Promoting my events
- [x] I only need Strapi swag

# Community Guidelines

- [x] I have read & agree to respect Strapi's [code of conduct](https://github.com/strapi/strapi/blob/master/CODE_OF_CONDUCT.md) and [community guidelines](https://github.com/strapi/strapi-meetups/blob/master/guidelines.md)
- [x] I have checked that there is no existing Strapi user group in this city.

**Comment by bigpreshy** [comment]
Updated

**Comment by vcoisne** [comment]
Hello @bigpreshy Thanks for creating this issue and sorry about the very late reply. We paused the meetup program due to covid and forgot to reply to issues individually. With the upcoming [StrapiConf](https://strapi.io/blog/announcing-strapi-conf-2023) we won't be able to support the creation of this group and provide all the help requested. Maybe it would make more sense to create a group for Nigeria and team up with other folks like @evergreenx who wanted to start a user group in Lagos?
