### ISSUE TITLE
Webinar #2 Topics

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi-meetups#2]
**Describe the topic**
As per our idea which surfaced during `Strapi Webinar strapi/strapi#1`, I would like to spark a thread/discussion on potentially relevant and useful topics/pain-points to discuss.

These topics would be answered by **S**ome **S**trapi **H**eroes - with answers being as solid as they get - since they will be delivered by/via (**SSH**). (_developer jokes?_)😺

**Your suggestions for this topic**
The intent of this thread is for anyone who has a pain-point, issue, specific question or something of the sort to have a place to post it, so the community could vote on the most popular ones.

- each posting could be voted for with "👍", "➕" etc - you know the drill...
- the topics with most likes could be answered first, the rest - depending on, you guessed it - the time remaining...
- for each webinar (regardless of how frequent/rare they end up being) we could open a new discussion to keep things organized
- anyone - more suggestions?

PS. Big thanks to Strapi team for putting together the first webinar earlier today. Cheers to everyone who was with us 🚀 ✋

**Comment by vcoisne** [comment]
The [3rd Online meetup](https://app.livestorm.co/strapi-1/everything-you-need-to-know-about-strapi-deployment-options) has been announced and will take place on Thursday, March 19th at 8:0 (PDT).

I will close this one now. We'll make sure to tweet out the next one so that we can get more suggestions and votes on topics :)
